[build-system]
requires = ["scikit-build-core>=0.10.0", "nanobind>=2.0.0", "setuptools-scm>=8"]
build-backend = "scikit_build_core.build"

[project]
name = "kamila"
dynamic = ["version"]
authors = [
  { name="Alexander Foss", email="alexanderhfoss@gmail.com" },
  { name="Marianthi Markatou"},
]
description = "Clustering Mixed-Type Data in Python and scikit-learn (KAMILA)"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "numpy>=1.22",
  "scipy>=1.8",
  "scikit-learn>=1.4.2",
  "joblib>=1.2",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
]

[project.urls]
Homepage = "https://github.com/ahfoss/scikit-kamila"
Issues = "https://github.com/ahfoss/scikit-kamila/issues"

[project.optional-dependencies]
test = [
  "pytest>=7.0",
  "pytest-cov>=4.0",
  "pandas>=1.4",
  "sphinx>=7.0,<7.3; python_version < '3.10'",
  "sphinx>=7.0; python_version >= '3.10'",
  "sphinx-gallery>=0.15",
  "pydata-sphinx-theme>=0.15",
  "numpydoc>=1.6",
  "sphinx-design>=0.5",
  "sphinx-prompt>=1.5",
  "matplotlib>=3.5",
  "pillow>=9.0",
]
lint = [
  "black>=23.3.0",
  "ruff>=0.4.0",
  "pre-commit>=3.0",
]
doc = [
  "sphinx>=7.0,<7.3; python_version < '3.10'",
  "sphinx>=7.0; python_version >= '3.10'",
  "sphinx-gallery>=0.15",
  "pydata-sphinx-theme>=0.15",
  "numpydoc>=1.6",
  "sphinx-design>=0.5",
  "sphinx-prompt>=1.5",
  "matplotlib>=3.5",
  "pillow>=9.0",
]
dev = [
  "pytest>=7.0",
  "pytest-cov>=4.0",
  "pandas>=1.4",
  "black>=23.3.0",
  "ruff>=0.4.0",
  "pre-commit>=3.0",
  "sphinx>=7.0,<7.3; python_version < '3.10'",
  "sphinx>=7.0; python_version >= '3.10'",
  "sphinx-gallery>=0.15",
  "pydata-sphinx-theme>=0.15",
  "numpydoc>=1.6",
  "sphinx-design>=0.5",
  "sphinx-prompt>=1.5",
  "matplotlib>=3.5",
  "pillow>=9.0",
]

[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
sdist.include = ["src/*", "CMakeLists.txt"]
wheel.packages = ["kamila"]

[tool.setuptools_scm]
write_to = "kamila/_version.py"
fallback_version = "0.1.0.dev0"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pixi.dependencies]
python = ">=3.9"
scikit-learn = ">=1.4.2"

[tool.pixi.pypi-dependencies]
kamila = { path=".", editable=true }

[tool.pixi.feature.lint.dependencies]
# The version below should be aligned with the one of `.pre-commit-config.yaml`
black = "23.3.0"
pre-commit = "3.7.1"
ruff = "0.4.2"

[tool.pixi.feature.lint.tasks]
black = { cmd = "black --check --diff kamila && black --check --diff examples" }
ruff = { cmd = "ruff check --output-format=full kamila && ruff check --output-format=full examples" }
lint = { depends_on = ["black", "ruff"]}

[tool.pixi.feature.test.dependencies]
pytest = "*"
pytest-cov = "*"

[tool.pixi.feature.test.tasks]
test = { cmd = "pytest -vsl --cov=kamila --cov-report=xml kamila" }

[tool.pixi.feature.doc.dependencies]
matplotlib = "*"
numpydoc = "*"
pydata-sphinx-theme = "*"
setuptools-scm = ">=8"  # needed for the versioning
sphinx = "*"
sphinx-design = "*"
sphinx-gallery = "*"
sphinx-prompt = "*"

[tool.pixi.feature.doc.tasks]
build-doc = { cmd = "make html", cwd = "doc" }
clean-doc = { cmd = "rm -rf _build", cwd = "doc" }

[tool.pixi.environments]
doc = ["doc"]
lint = ["lint"]
test = ["test"]
dev = ["doc", "lint", "test"]

[tool.black]
line-length = 88
target_version = ['py38', 'py39', 'py310']
preview = true
exclude = '''
/(
    \.eggs         # exclude a few common directories in the
  | \.git          # root of the project
  | \.vscode
  | \.venv
)/
'''
force-exclude = "kamila/_version.py"

[tool.ruff]
# max line length for black
line-length = 88
target-version = "py38"
exclude=[
    ".git",
    ".venv",
    "__pycache__",
    "dist",
    "doc/_build",
    "doc/auto_examples",
    "build",
    "kamila/_version.py",
]


[tool.ruff.lint]
# all rules can be found here: https://beta.ruff.rs/docs/rules/
select = ["E", "F", "W", "I"]
ignore=[
    # space before : (needed for how black formats slicing)
    "E203",
    # do not assign a lambda expression, use a def
    "E731",
    # do not use variables named 'l', 'O', or 'I'
    "E741",
]

[tool.ruff.lint.per-file-ignores]
# It's fine not to put the import at the top of the file in the examples
# folder.
"examples/*"=["E402"]
"doc/conf.py"=["E402"]
"doc/_templates/numpydoc_docstring.py"=["F821", "W292"]

[tool.pytest.ini_options]
testpaths = ["kamila"]
norecursedirs = ["doc", "examples", "scripts", ".git", "build", "dist"]
addopts = "--doctest-modules --color=yes"
doctest_optionflags = "NORMALIZE_WHITESPACE"
filterwarnings = [
    "error",
    "ignore::coverage.exceptions.CoverageWarning",
]

[tool.coverage.run]
source = ["kamila"]
disable_warnings = ["include-ignored"]
omit = [
    "*/tests/*",
    "*_version.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "except ImportError:",
    "if __name__ == .__main__.:",
]
show_missing = true
precision = 2
fail_under = 100
